<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>benchmark_client</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Gera.Chess" Version="1.2.0" />
      <PackageReference Include="ManagedCuda-Nvml.NETStandard" Version="9.1.300" />
      <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
    </ItemGroup>

</Project>
